# Introduction

Pokémon Scarlet and Pokémon Violet will be the first open-world RPG in the Pokémon series focused on the ninth generation of games with a release date of 2022. 

The overall goal here is to note any potential correlations between base stats and select pokemon accordingly. I'm hoping to find some well-balanced types rather than one-note wonders.

I will try to found the best team, according of adventure or competitive game.

I hope what this analysis help you if you want to play this game.

![](./img/logo.jpg)



# Import Libraries and Loading Data

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

pokemons = pd.read_csv('gen9_data.csv')

In [1]:
import pandas as pd

In [2]:
pokemons = pd.read_csv('gen9_data.csv')
pokemons.head()

Unnamed: 0              Pokémon    H    A    B    C    D    S  Total
0           0             Koraidon  100  135  115   85  100  135    670
1           1             Miraidon  100   85  100  135  115  135    670
2           2              Slaking  150  160  100   95   65  100    670
3           3  Palafin (Hero Form)  100  160   97  106   87  100    650
4           4             Garchomp  108  130   95   80   85  102    600

# Cleansing Data

In [3]:
pokemons = pokemons.drop('Unnamed: 0',axis=1)

In [4]:
pokemons.columns

Index(['Pokémon', 'H', 'A', 'B', 'C', 'D', 'S', 'Total'], dtype='object')

In [5]:
column_map = {
    'Pokémon':'Pokemon',
    'H':'HP',
    'A':'Attack',
    'B':'Defense',
    'C':'Special_Attack',
    'D':'Special_Defense',
    'S': 'Speed'
}
pokemons = pokemons.rename(columns=column_map)
pokemons.head()

Pokemon   HP  Attack  Defense  Special_Attack  Special_Defense  \
0             Koraidon  100     135      115              85              100   
1             Miraidon  100      85      100             135              115   
2              Slaking  150     160      100              95               65   
3  Palafin (Hero Form)  100     160       97             106               87   
4             Garchomp  108     130       95              80               85   

   Speed  Total  
0    135    670  
1    135    670  
2    100    670  
3    100    650  
4    102    600

# Exploration

In [6]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431 entries, 0 to 430
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Pokemon          431 non-null    object
 1   HP               431 non-null    int64 
 2   Attack           431 non-null    int64 
 3   Defense          431 non-null    int64 
 4   Special_Attack   431 non-null    int64 
 5   Special_Defense  431 non-null    int64 
 6   Speed            431 non-null    int64 
 7   Total            431 non-null    int64 
dtypes: int64(7), object(1)
memory usage: 27.1+ KB


In [7]:
pokemons.describe()

HP      Attack     Defense  Special_Attack  Special_Defense  \
count  431.000000  431.000000  431.000000      431.000000       431.000000   
mean    70.364269   76.269142   67.907193       67.897912        67.111369   
std     27.936964   29.587347   26.313331       28.245910        24.744586   
min     10.000000    5.000000    5.000000       10.000000        20.000000   
25%     50.000000   55.000000   50.000000       45.000000        50.000000   
50%     68.000000   70.000000   65.000000       61.000000        65.000000   
75%     84.000000  100.000000   80.000000       90.000000        81.000000   
max    255.000000  160.000000  184.000000      140.000000       154.000000   

            Speed       Total  
count  431.000000  431.000000  
mean    67.248260  416.368910  
std     28.263315  107.564479  
min     10.000000  180.000000  
25%     45.000000  315.000000  
50%     65.000000  450.000000  
75%     86.000000  500.000000  
max    150.000000  670.000000

I look in the column HP of max points is 255 base, I think that is a much difference with the 75% percentil of 85 points. That difference max of 100 points.

Looks that Pokemon is

In [8]:
max_hp = pokemons[pokemons['HP'] == 255]
max_hp

Pokemon   HP  Attack  Defense  Special_Attack  Special_Defense  Speed  \
36  Blissey  255      10       10              75              135     55   

    Total  
36    540

In the game Blissey is known as a tank pokemon, Hp and Special_Defense are perfect for tank equipment or support moves.


<img src="./img/blissey.png" alt="blissey" width="300"/>


[Blissey Pokedex](https://www.pokemon.com/el/pokedex/blissey)

I think is better and I'l much more interested in getting balanced pokemon with higher stats than pokemon with one max stat like Blissey. That thing only has 10 attack and defense!

In [9]:
pokemons.corr(numeric_only=True)

HP    Attack   Defense  Special_Attack  \
HP               1.000000  0.409537  0.308370        0.226825   
Attack           0.409537  1.000000  0.538072        0.195436   
Defense          0.308370  0.538072  1.000000        0.278458   
Special_Attack   0.226825  0.195436  0.278458        1.000000   
Special_Defense  0.392720  0.257561  0.436017        0.576819   
Speed            0.058279  0.329706  0.088310        0.365254   
Total            0.616330  0.712152  0.662721        0.665763   

                 Special_Defense     Speed     Total  
HP                      0.392720  0.058279  0.616330  
Attack                  0.257561  0.329706  0.712152  
Defense                 0.436017  0.088310  0.662721  
Special_Attack          0.576819  0.365254  0.665763  
Special_Defense         1.000000  0.268583  0.724324  
Speed                   0.268583  1.000000  0.544759  
Total                   0.724324  0.544759  1.000000

These are all at least weakly correlated and many are moderately correlated. I will focus on the stronger correlations I find. In terms of the weaker ones, Speed is only moderately correlated with Total and has weaker ties to the other stats as well. 

* HP -- Moderately correlated with Attack, Defense, and Special Defense.
* Attack -- strongly correlated with Defense. Moderately correlated with Speed and HP. Slightly more strongly correlated with HP than Defense is.
* Defense -- Strongly correlated with Attack. Moderately correlated with Special Defense and HP.
* Special Attack -- Strongly correlated with Special Defense. Moderately correlated with Speed.
* Special Defense -- Strongly correlated with Special Attack. Moderately correlated with Defense and HP.
* Speed -- Weakest correlations of the bunch. Moderately correlated with Special Attack and Attack

In my opinion this correlation has logic,you need Speed to Attack effectively, right? Weirdly, every stat but Special Attack has at least a moderate correlation with HP. 

**Is important know that its a difference to play with a team in aventure mode that a competitive mode, in this analysis I will search a better team for this modes.**



# Aventure Game

## Initial Pokemon

In the aventure game we started with the option chosse a initial pokemon.

The initial pokemons are:

**Sprigatito**

<img src="./img/first.png" width="300"/>


**Fuecoco**

<img src="./img/second.png" width="300"/>


**Quaxly**

<img src="./img/third.png" width="300"/>



In [10]:
initials = ['Sprigatito','Fuecoco','Quaxly']

pokemons.query('Pokemon in @initials')

Pokemon  HP  Attack  Defense  Special_Attack  Special_Defense  Speed  \
329  Sprigatito  40      61       54              45               45     65   
330     Fuecoco  67      45       59              63               40     36   
331      Quaxly  55      65       45              50               45     50   

     Total  
329    310  
330    310  
331    310

Three pokemons initials have a total points stats same, but in game we prefer the speed and attack stats.

In the ultimate form the stats for initials pokemon are:

In [11]:
ultimates = ['Meowscarada','Skeledirge','Quaquaval']

pokemons.query('Pokemon in @ultimates')

Pokemon   HP  Attack  Defense  Special_Attack  Special_Defense  Speed  \
46  Meowscarada   76     110       70              81               70    123   
47   Skeledirge  104      75      100             110               75     66   
48    Quaquaval   85     120       80              85               75     85   

    Total  
46    530  
47    530  
48    530

**My recomendation for initial pokemon is Sprigatito**

One pokemon with types are grass and dark in the ultimate evolution

<img src="./img/first.png" width="300"/>

[Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Sprigatito_(Pok%C3%A9mon))

In [35]:
initial = pokemons[pokemons['Pokemon'] == 'Sprigatito']

names = ['HP','Attack','Defense','Special_Attack','Special_Defense','Speed']
values = [40,61,54,45,45,65]

px.pie(initial,names=names,values=values,title='Stats of Initial').show()


## Special_Attack and Speed

In [42]:
ax1 = px.scatter(pokemons,x='Speed',y='Special_Attack',color='Pokemon',title='Correlation between Speed and Special Attack')
ax1.show()

Considering the correlation in Special Attack and Speed I think that a pokemon with Stats > 120 in two stats are the best option

In [41]:
mask = (pokemons['Special_Attack'] >= 120)&(pokemons['Speed']>=120)

options_second = pokemons[mask]

options_second

Pokemon   HP  Attack  Defense  Special_Attack  Special_Defense  \
1       Miraidon  100      85      100             135              115   
18  Flutter Mane   55      55       55             135              135   
25   Iron Bundle   56      80      114             124               60   

    Speed  Total  
1     135    670  
18    135    570  
25    136    570

**Miraidon is the legendary pokemon of the Violet version so I wouldn't consider it for adventure**

## Defense and Special_Defense

In [43]:
ax2 = px.scatter(pokemons,x='Defense',y='Special_Defense',color='Pokemon',title='Correlation between Defense and Special Defense')
ax2.show()

It is necessary to be able to have a tank or support pokemon to propose different strategies such as state movements, although in the adventure it will not be so necessary since we need speed priority and attacks, although it is not bad for difficult moments as for the pokemon league. Consider having at least 110 points from each stat.

In [46]:
mask = (pokemons['Special_Defense'] >= 110)&(pokemons['Defense']>=110)

options_third = pokemons[mask]

options_third

Pokemon  HP  Attack  Defense  Special_Attack  Special_Defense  Speed  \
53    Umbreon  95      65      110              60              130     65   
101  Bronzong  67      89      116              79              116     33   
115   Toxapex  50      63      152              53              142     35   

     Total  
53     525  
101    500  
115    495

I considering Umbreon or Toxapex , Umbreon is most equilibrated but Toxapex Defenses are the best of game